[package]
name = "bull-bitcoin-export-fix"
version = "0.1.0"
edition = "2021"
authors = ["Steven Black"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1"
